### ISSUE TITLE
Value Color is invisible

### ISSUE THREAD

**Issue by marowsky** [hotNipi/node-red-contrib-ui-artless-gauge#1]
The Value Color is invisible.

![Anmerkung 2020-03-14 150720](https://user-images.githubusercontent.com/15909379/76683884-ba064a00-6607-11ea-8730-53a2c8fc4f9c.jpg)

**Environment and versions**

- RedMatic Version: 5.5.2
- Node-Red version: 1.0.4
- dashboard version: 2.19.4
- ui-artless-gauge version: 0.1.9

**Comment by hotNipi** [comment]
Redmatic is not standard solution so can't even comment. Try to rise issue against the redmatic
