### ISSUE TITLE
Problem with asymmetric range (differential mode)

### ISSUE THREAD

**Issue by kais0r** [hotNipi/node-red-contrib-ui-artless-gauge#10]
When using differential mode and asymmetric range, there is a problem with the zero marking.
(Either zero marking or gauge behaviour)

When using a Range for example of -100 ... 300, then it behaves like this:
![Screenshot 2020-04-22 at 14 46 47](https://user-images.githubusercontent.com/42624158/79983455-1c285980-84a8-11ea-9595-efcd799a9cf5.png)

![Screenshot 2020-04-22 at 14 47 17](https://user-images.githubusercontent.com/42624158/79983533-32ceb080-84a8-11ea-8059-e85a76d398f5.png)

![Screenshot 2020-04-22 at 14 47 53](https://user-images.githubusercontent.com/42624158/79983571-437f2680-84a8-11ea-87ee-cde098125a6d.png)

![Screenshot 2020-04-22 at 14 56 02](https://user-images.githubusercontent.com/42624158/79984417-6bbb5500-84a9-11ea-8086-2b82ff761a2c.png)

In this example it has its virtual zero at +100. so Values smaller than 100 look like negative values.

There would be 2 Options to solve:
1. Set zero mark to the real zero position of the range and start graph from this value
2. or split ranges from the middle.

Snippet of this example:
`[{"id":"f9a45330.89b66","type":"ui_artlessgauge","z":"31363699.ff5a5a","group":"556c6fb0.b3e62","order":10,"width":0,"height":0,"name":"Fv","icon":"","label":"Fv","unit":"Newton","layout":"linear","decimals":0,"differential":true,"minmax":true,"colorTrack":"#555555","colorFromTheme":true,"sectors":[{"val":-100,"col":"#00f900","t":"min","dot":0},{"val":120,"col":"#fffb00","t":"sec","dot":0},{"val":220,"col":"#ff2600","t":"sec","dot":0},{"val":300,"col":"#ff2600","t":"max","dot":0}],"lineWidth":3,"bgcolorFromTheme":true,"x":1030,"y":1900,"wires":[]},{"id":"5505797f.50e388","type":"ui_slider","z":"31363699.ff5a5a","name":"","label":"slider","tooltip":"","group":"556c6fb0.b3e62","order":9,"width":0,"height":0,"passthru":true,"outs":"end","topic":"","min":"-100","max":"300","step":"1","x":790,"y":1900,"wires":[["f9a45330.89b66"]]},{"id":"556c6fb0.b3e62","type":"ui_group","z":"","name":"Modulbrücke 3 (West)","tab":"a7f6e62d.f7a4d8","order":4,"disp":true,"width":"6","collapse":false},{"id":"a7f6e62d.f7a4d8","type":"ui_tab","z":"","name":"Kraft","icon":"dashboard","order":4,"disabled":false,"hidden":false}]`

**Comment by hotNipi** [comment]
I can't see the issue or I'm missing something?
As sated in documentation - Value of center point is exactly between configured min and max. 

From -100  to 300 makes center point to be exactly 100.
Scale of track is linear and I can't see any way to change this..  

!! The center value can be shown if you configure the unit field empty.

What I discovered during this is that with value === 0 the gauge shows min value (-100). That is bug and will be fixed immediately. Thank you for pointing me to discover this.

**Comment by hotNipi** [comment]
If you want to have zero marked on track with uneven configuration you can show the dot on that point. And if you don't want to change the line color when crossing the zero, there is a little configuration trick.

![image](https://user-images.githubusercontent.com/35291460/80033929-35f08d80-84f6-11ea-95a4-1fd26f6f8ee0.png)

![image](https://user-images.githubusercontent.com/35291460/80034093-810aa080-84f6-11ea-874f-ab63ed1fdf93.png)

**Comment by kais0r** [comment]
Hi. Maybe it's not an issue if you did it on purpose :-).

It would be great to have an option that the line starts drawing from 0 (or any value between min and max), and not only from (config.min+config.max)/2.

Does this clearify what i mean?

**Comment by kais0r** [comment]
Here is another example:
If i have 5kW Peak solar panels on my roof, and i want to gauge the main PowerMeter, then i would have a min power of -5kW and a max of 15kW.

When consuming 0.2kW, i want the Graph to be very tiny, almost 0.
At the moment the graph would be as big as representing 4.8kW:

![Screenshot 2020-04-22 at 23 27 49](https://user-images.githubusercontent.com/42624158/80035852-055a2500-84f1-11ea-869a-f9c148235ae9.png)

Edit:
When enabling differential mode, having an option to select the Start Point which can be **Center** or **custom** would be AMAZING!

**Comment by kais0r** [comment]
Here is a Sub-Issue (i don't want to make a new one, because i think it's the same code area)

In differential mode, the left hand side range marks have the wrong color.
Since the graph comes form the right hand side, the range marking should have the color of the
next range color. (The graph-color itself behaves correctly).

![Screenshot 2020-04-22 at 23 55 06](https://user-images.githubusercontent.com/42624158/80038069-202e9880-84f5-11ea-9bb2-06cc75f06cbd.png)

![Screenshot 2020-04-23 at 00 06 59](https://user-images.githubusercontent.com/42624158/80038687-72bc8480-84f6-11ea-809c-90b11dd75719.png)

Edit: Sorry if i am too miserly

**Comment by hotNipi** [comment]
Well. I'll try to explain why it is bad idea. This is how it may look like.  
![image](https://user-images.githubusercontent.com/35291460/80061234-6279c900-8539-11ea-8dd2-1be781d39fd7.png)

Try to look at it like you just walked in the control room and at first look  to the screen instantly understand what this gauge tries to tell to you. 
Very hard. Gauge in this situation is pretty unreadable. 

And also, same functionality must be available for radial mode and this may turn out more confusing ....

But I am not telling that it is impossible to do. To convince me to add this option, it needs a bit wider support. So if you start a thread in https://discourse.nodered.org/ and there will be more support to your idea, I will implement it as an option.



The sub issue

About the sub issue (colors order in configuration) I knew it will rise at some day. But there is not much I can do about it. It is the way of thinking. You are thinking about two sides and moving to that direction, But there is only one line with mathematical order of marked points. 

Can only advise to think linear and then it makes sense.

**Comment by kais0r** [comment]
I understand, but if you think about my example:
![80035852-055a2500-84f1-11ea-869a-f9c148235ae9](https://user-images.githubusercontent.com/42624158/80063148-8a672d80-8535-11ea-8c75-687cc33b6229.png)

If you walk my control room, first thing you think: "hell, why is there a power activity?".

1: Off-Center-Graph-starting-point:
![AsymZeroPos](https://user-images.githubusercontent.com/42624158/80065501-88ec3400-853a-11ea-9825-f384e338d85f.png)


I understand what you are trying to say. I think it depends on the case of use.
In my case of use your example would be what i want to see. 
But i agree that it would be more convinient if everything starts from center for most applications.

I think the solution to both our opinions would be asymmetric scale factors.
But in my opinion this is a bad idea, too:

2: Asymmetric scale factors:
![AsymScale](https://user-images.githubusercontent.com/42624158/80065661-c94bb200-853a-11ea-9513-a31a3072e888.png)




Having a option for setting the "Off-Center-Graph-starting-point" (1) would be cool.

**Comment by kais0r** [comment]
The sub issue:

For non-differential mode i agree.
But when enabling differential-mode the interpretation (or thinking) is differential.

Graph goes from Center to the right and from center to the left. So it is "mirrored" from the center point.

But i agree that it is too complicated to make such detailed differences. Let's forget about the sub-isue.

**Comment by hotNipi** [comment]
Your examples of course make sense. But now let's go to the complicated area. The edge cases.
1. As center point is free to move where you want, lets place it very near to edge. (preserve readability)
2. Radial layout - runs out of space so nowhere to place the marker 
![image](https://user-images.githubusercontent.com/35291460/80067801-32d1bd80-8547-11ea-88b7-db541ec593a3.png)

**Comment by hotNipi** [comment]
Th other thing. Differential mode around the "best" value. What i mean is again the readability - if the balanced situation is considered the best, the colored line is tiny dot. That is most unreadable situation. 
I put in another example to explain myself 
I have seen same issue many times with people doing with battery indicator. If battery goes empty, the gauge shows no value (or small dot in edge). But situation is for opposite - critical. So should be red and big to indicate it.

**Comment by kais0r** [comment]
1. there is always a way to configure it wrong. I thing the users of this nice gauge are not that untalented.

2. you are right. Maybe asymmetric scale fators make sense in Radial Layout.
 (if there would be space for the Center Marker value in Linear Layout, it would be good, too)

What if: When enabling "Set Center Value":
- in radial layout, it makes different scale factors.
- in linear layout, it moves the start point, but keeps identical scale factors.

**Comment by hotNipi** [comment]
3. (Linear).  There is no value shown at that point to indicate what the value is. There is option to show value at that point (same manner as min and max). Now lets move the point near to edge and lets then deal with values in scale of 10000. And lets try to figure out how to not overlap them....

**Comment by kais0r** [comment]
There are endless examples for both pro and contra side.
Thats why an option to enable it would be prefered.

Showing the SOC of a battery: 
When you use the non differential mode, There is this "problem" you mentions as well... 
Having no graph at for example 5% SOC then its not good as well, because u think 
browser does not function corretly.

Showing 0 is always critical. But i think most users know about that.

Maybe where whould always be at least 1px shown? But this is another issue i think.

Edit:
If your Lithium-Ion battery has 0% SOC for a long time it is dead anyway :-D
You need some heavy push messages when getting below 5%

**Comment by kais0r** [comment]
to 3:
I agree... but this is a static configuration. Users (programmers) must take care about that.
When showing such high values, most people consider to take the next decades....

I understand your point of view. you want to keep it simple to use. And thats good.
I want to help to make it more suitable for even more situations, because its a really good gauge!

**Comment by hotNipi** [comment]
:) Just with half an hour of discussion about seamlessly simple option and the issue list with  grows to the heaven. 
I'm not against it. But as you see .. many things to take account (and then to explain to public why some things can't be done)

But before to go on, I still need to think the possibility of it with radial layout. That is much more complicated thing as you can imagine.

**Comment by hotNipi** [comment]
So I think I can do following:
The breaking point for differential mode can be even in the middle (current solution) or zero (0), but not any other custom value in range.

![image](https://user-images.githubusercontent.com/35291460/80076344-be058000-8554-11ea-88f0-9176de60a4d0.png)

Ignore the radial in that image cos this is just tweaked graphics, no code changes (just indicates where zero point will go to get the ideas about what will happen)

Why only the zero? Because of all other possible configurations will create too many cases for fitting the elements and lead to overlaps and many other such side issues from layout perspective.

But if so limited, is it worth of doing at all??

At this point the topic started for more input at https://discourse.nodered.org/t/artless-gauge-features-i-need-second-and-third-opinion/25361

**Comment by hotNipi** [comment]
So  something I did. You can move the cross point when in differential mode. Freely. 
Before to publish, Id like to get some comments.
Install it from git to try

**Comment by hotNipi** [comment]
Version 0.1.25 published

- Adjustable center value for differential mode
- Fixed low-end dot colors for differential mode

**Comment by kais0r** [comment]
Sorry for my late reply. It's working perfect! I Really appreciate the quick implementation of this feature. Thanks so much!
