### ISSUE TITLE
Problem with 0 value in differential mode

### ISSUE THREAD

**Issue by kais0r** [hotNipi/node-red-contrib-ui-artless-gauge#11]
When using differential mode and having a symmetric and negative to positive range (for example -60...+60) then the gauge always displays the min value when sending numeric 0.

Workaround:  send 0.01  (1E-(digits+1))

![Screenshot 2020-04-22 at 22 17 34](https://user-images.githubusercontent.com/42624158/80029603-4cdbb380-84e7-11ea-8dc3-446d089bbdc4.png)

![Screenshot 2020-04-22 at 22 21 39](https://user-images.githubusercontent.com/42624158/80029852-a9d76980-84e7-11ea-98d2-cb561c182085.png)

![Screenshot 2020-04-22 at 22 18 31](https://user-images.githubusercontent.com/42624158/80029617-536a2b00-84e7-11ea-99c6-fb4feeac7ba1.png)

Snippet to test:
`[{"id":"8acdf134.9d16a","type":"ui_artlessgauge","z":"31363699.ff5a5a","group":"32005d35.ce3ca2","order":6,"width":0,"height":0,"name":"Winkel","icon":"","label":"Winkel","unit":"deg","layout":"linear","decimals":"0","differential":true,"minmax":true,"colorTrack":"#555555","colorFromTheme":true,"sectors":[{"val":-60,"col":"#00f900","t":"min","dot":0},{"val":60,"col":"#00f900","t":"max","dot":0}],"lineWidth":3,"bgcolorFromTheme":true,"x":610,"y":2000,"wires":[]},{"id":"8e3cc3b4.c4ea2","type":"inject","z":"31363699.ff5a5a","name":"","topic":"","payload":"0","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":370,"y":1940,"wires":[["57beecf8.924d14","8acdf134.9d16a"]]},{"id":"a2773f4d.69a7e","type":"inject","z":"31363699.ff5a5a","name":"","topic":"","payload":"0.001","payloadType":"num","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":370,"y":2000,"wires":[["57beecf8.924d14","8acdf134.9d16a"]]},{"id":"57beecf8.924d14","type":"debug","z":"31363699.ff5a5a","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":610,"y":1940,"wires":[]},{"id":"ceeda992.b1cc78","type":"ui_slider","z":"31363699.ff5a5a","name":"","label":"Test:","tooltip":"","group":"32005d35.ce3ca2","order":5,"width":0,"height":0,"passthru":true,"outs":"end","topic":"","min":"-1","max":"1","step":"0.01","x":370,"y":2060,"wires":[["8acdf134.9d16a"]]},{"id":"32005d35.ce3ca2","type":"ui_group","z":"","name":"Wetter","tab":"a7f6e62d.f7a4d8","order":1,"disp":true,"width":"6","collapse":false},{"id":"a7f6e62d.f7a4d8","type":"ui_tab","z":"","name":"Kraft","icon":"dashboard","order":4,"disabled":false,"hidden":false}]`

**Comment by hotNipi** [comment]
Fixed in v0.1.24
