### ISSUE TITLE
No more bar displayed

### ISSUE THREAD

**Issue by Eddy-Go** [hotNipi/node-red-contrib-ui-artless-gauge#12]
After the update to v0.1.41 no bar is displayed for Layout Linear.
Mode differential shows something.
Need more info?
best regards
Eddy

Flow:
[{"id":"4e4c7c43.1527c4","type":"ui_slider","z":"2b297c36.8c7694","name":"","label":"slider","tooltip":"","group":"403d4239.5aa044","order":10,"width":0,"height":0,"passthru":true,"outs":"all","topic":"","min":"0","max":"10000","step":"50","x":270,"y":740,"wires":[["b3b1774b.ed1a08","1162130d.1898ad","f1c5a7df.cea6f","a2e0551f.481f78"]]},{"id":"1162130d.1898ad","type":"ui_level","z":"2b297c36.8c7694","group":"403d4239.5aa044","order":11,"width":0,"height":0,"name":"Batterie","label":"Batterie","colorHi":"#e60000","colorWarn":"#ff9900","colorNormal":"#00b33c","colorOff":"#595959","min":0,"max":"10000","segWarn":"","segHigh":"","unit":"Volt","layout":"sh","channelA":"","channelB":"","decimals":0,"animations":"rocket","shape":"3","colorschema":"valuedriven","textoptions":"default","colorText":"#eeeeee","fontLabel":"","fontValue":"","fontSmall":"","colorFromTheme":true,"textAnimations":true,"hideValue":false,"tickmode":"off","peakmode":false,"peaktime":3000,"x":460,"y":780,"wires":[]},{"id":"f1c5a7df.cea6f","type":"ui_artlessgauge","z":"2b297c36.8c7694","group":"403d4239.5aa044","order":9,"width":0,"height":0,"name":"","icon":"","label":"Gauge","unit":"","layout":"linear","decimals":0,"differential":false,"minmax":true,"colorTrack":"#555555","colorFromTheme":true,"property":"payload","sectors":[{"val":0,"col":"#ff9900","t":"min","dot":0},{"val":5000,"col":"#ff6666","t":"sec","dot":0},{"val":10000,"col":"#ff6666","t":"max","dot":0}],"lineWidth":"7","bgcolorFromTheme":true,"diffCenter":"1","x":480,"y":720,"wires":[]},{"id":"a2e0551f.481f78","type":"ui_artlessgauge","z":"2b297c36.8c7694","group":"403d4239.5aa044","order":9,"width":0,"height":0,"name":"","icon":"","label":"Gauge","unit":"","layout":"radial","decimals":0,"differential":false,"minmax":true,"colorTrack":"#555555","colorFromTheme":true,"property":"payload","sectors":[{"val":0,"col":"#ff9900","t":"min","dot":0},{"val":5000,"col":"#ff6666","t":"sec","dot":0},{"val":10000,"col":"#ff6666","t":"max","dot":0}],"lineWidth":"7","bgcolorFromTheme":true,"diffCenter":"1","x":480,"y":680,"wires":[]},{"id":"403d4239.5aa044","type":"ui_group","z":"","name":"Status","tab":"4b1c44b3.2e9814","order":1,"disp":true,"width":"6","collapse":false},{"id":"4b1c44b3.2e9814","type":"ui_tab","z":"","name":"Batterie","icon":"dashboard","order":1,"disabled":false,"hidden":false}]

**Comment by Eddy-Go** [comment]
![grafik](https://user-images.githubusercontent.com/65780852/82691448-35b2f180-9c5e-11ea-9e23-836e7a17613d.png)

**Comment by hotNipi** [comment]
Is it on the iOS device?

**Comment by Eddy-Go** [comment]
It is a Window 10 computer. Dashboard is viewed with Firefox.
The other system is a Raspberry Pi with Raspberrymatic and the Addon Node-Red.

Both systems were running before the update.

![grafik](https://user-images.githubusercontent.com/65780852/82711272-2bf0b480-9c85-11ea-8ae2-a6d2f41769ed.png)

**Comment by hotNipi** [comment]
Have you updated ui_level also?
Do you see any errors in browser console?

**Comment by Eddy-Go** [comment]
I have installed Ui_Level only on the Win10 system which I have not updated.
I can't see any unusual messages in the console.

I first updated the raspberry system, where I saw the display error. Then I updated the win-PC, which is only a test system for me. That's when I saw the error.

When I switch the node to differential mode you can see the bar, so it can't be the browser!
![grafik](https://user-images.githubusercontent.com/65780852/82725752-7737b100-9cdf-11ea-8d67-86a524151a80.png)

**Comment by Eddy-Go** [comment]
I have now noticed that when I refresh Firefox with F5 there is now a bar.

Change value with the slicer.
![grafik](https://user-images.githubusercontent.com/65780852/82725889-8834f200-9ce0-11ea-98b2-7866168769ad.png)
Refresh firefox with F5
![grafik](https://user-images.githubusercontent.com/65780852/82725907-adc1fb80-9ce0-11ea-972e-36f759009333.png)

**Comment by hotNipi** [comment]
It is known that first message after you add widget to the dashboard or if you are changing the widget shape of widget will not produce the bar rendering. This is due the "replayMesssage" (node-red internal therm). 
But any other message should produce bar and that was weird. 

Anyway, your last input shows that it is working but is it for both your systems or only for windows?

**Comment by hotNipi** [comment]
Also, after updating the widget, it is recommended to clear the browser cache. It may happen that some old cached values may not be suitable to new version of widget.

**Comment by Eddy-Go** [comment]
With the Raspbery system the bars are sporadically refreshed !
![grafik](https://user-images.githubusercontent.com/65780852/82726261-0db9a180-9ce3-11ea-8404-b3154bd6f9d9.png)
F5
![grafik](https://user-images.githubusercontent.com/65780852/82726275-2d50ca00-9ce3-11ea-88ae-12a863f447d4.png)
F5
![grafik](https://user-images.githubusercontent.com/65780852/82726282-39d52280-9ce3-11ea-94a6-caa9526e802d.png)

**Comment by Eddy-Go** [comment]
Why does autorefresh work in differential mode ? 
Then it cannot be the browser...

**Comment by hotNipi** [comment]
Ok. that's different and known. If you do refresh, the widgets are created again on the page and that is now depends on machine and browser how quickly they are ready to take data. Data from serverside may come earlier than the widget is ready to render the bar. In those cases, the rendering fails and it waits for next data income. 
I tried to improve that area but it's not that easy. It is my stupidity to create linear and radial layout into one widget. That creates another layer of difficulties on that same area. So yes. known, improved many times, but still a bit not there.

**Comment by Eddy-Go** [comment]
Maybe other users who also have such a problem will get in touch.
Thanks for your effort.

**Comment by Eddy-Go** [comment]
after a downgrade to version 0.1.40 all functions are available again.
![grafik](https://user-images.githubusercontent.com/65780852/82747240-4f0b8900-9d97-11ea-852f-0293600a9927.png)
![grafik](https://user-images.githubusercontent.com/65780852/82747251-65194980-9d97-11ea-90fd-1e89f9aa2c78.png)
The bar is automatically refreshed and displayed correctly.
This downgrade can only be done on my test system, I have no possibility to do it on my productive system.

Please check your source code again.

Thanks for your effort.

**Comment by Eddy-Go** [comment]
When comparing the versions of 0.1.40 and 0.1.41 I noticed that they use different libraries from greensock.com (version GSAP 3.2.2 to GSAP 3.2.6). Maybe this is the reason for the change of the bar display?

**Comment by hotNipi** [comment]
Yes. Library is updated to latest. There is ongoing issue with iOS devices and I've no devices to debug it, so I did everything reasonable to try to fix it but no success. But that library change is not main change, there is change in the init phase which most probably makes that difference.

**Comment by hotNipi** [comment]
Earlier you said: When I switch the node to differential mode you can see the bar, so it can't be the browser!
Is this still true for 0.1.41? There may be some clues if it is that way.
I ask cos for me the issue does not reproduce.

**Comment by Eddy-Go** [comment]
The differential mode is displayed correctly in all versions, also in 0.1.41
![grafik](https://user-images.githubusercontent.com/65780852/82748953-3191eb80-9da6-11ea-8139-bb28fd69fef6.png)

**Comment by hotNipi** [comment]
OK. I have an update coming soon. Let's try.

**Comment by hotNipi** [comment]
v0.1.42 published

**Comment by Eddy-Go** [comment]
The display in v0.1.42 is again in order
Thanks
The issue can be closed.
