### ISSUE TITLE
Feature-request: Support icofont

### ISSUE THREAD

**Issue by jeroenst** [hotNipi/node-red-contrib-ui-artless-gauge#13]
I want to use icons (washing machine) that are not available in the icon libs provided by artless gauge.
Is it possible to include https://icofont.com/ ?

**Comment by hotNipi** [comment]
Full icon font support is too expensive thing to bake into  custom widget. The thing to consider might be to support custom icon somehow. Not easy to implement and somehow feels time that it will then be like partial support which again is not nice.

**Comment by hotNipi** [comment]
Closing this as for today there is support for iconify icons
