### ISSUE TITLE
Differential Mode Colors

### ISSUE THREAD

**Issue by Bono1969** [hotNipi/node-red-contrib-ui-artless-gauge#14]
Hi, your artless gauge is exactly what i searched for, with one issue.
When you use the gauge in differential mode it should be possible to set the color for the max value also.

for me it should work as follows:

from 0 to "lower"seg or "higher"seg it should be green (that works)
from "lower" seg to min value it should be red (that Works)
from "higher"seg to max value it should be red (not possible)

maybe you can change that.
Regards

**Comment by Bono1969** [comment]
Update:
from 0 to the lower Side it works perfekt.
from 0 to the upper Side the colors do not correspond with the settings (also the Seg colors)
![Gauge Colors](https://user-images.githubusercontent.com/37637519/88634950-53199700-d0b7-11ea-9f39-e396fed4bea8.png)
![Gauge wrong Color](https://user-images.githubusercontent.com/37637519/88634972-5ca2ff00-d0b7-11ea-8534-a2b6d4c88a5f.png)

**Comment by hotNipi** [comment]
It is confusing but not impossible.
It takes to think about the segments creation in linear way. From lowest to highest. 
I'd guess your setup should be like this

![image](https://user-images.githubusercontent.com/35291460/88636203-4306b500-d0c1-11ea-8047-7ccb8ba5c696.png)

You don't need to declare segment for 0 unless you need to make dot on that point.

**Comment by Bono1969** [comment]
the point with the Sec (0) was a try which didn't work 😊
when i arrange the colors in the way you showed it works PERFECT!
Thanks allot 👍

**Comment by hotNipi** [comment]
Thank you :)
