### ISSUE TITLE
Visibility

### ISSUE THREAD

**Issue by Bono1969** [hotNipi/node-red-contrib-ui-artless-gauge#15]
hi, again
i know, that this should be a smooth (artless) Design.
For bigger Screens or bigger Distances the visibility is very small.
Could there be more Values in the "Line width" setting?
![Value Trail Grafik](https://user-images.githubusercontent.com/37637519/88650437-063ebc00-d0c9-11ea-8c76-2d0ea23b99ff.png)

**Comment by hotNipi** [comment]
For linear layout it just runs out of space. To make it support more than 1 unit in height seems quite of challenge. 
For radial layout it may be possible to go let's say up to 15px line width. It then creates another possible issue with tickmark positions and can possibly overlap. And it definitely will make mess for smaller sizes. 

![image](https://user-images.githubusercontent.com/35291460/88658500-36dc2100-d0dc-11ea-8746-06c65fc1dfa9.png)


So the configuration options should dynamically change according to configured size. Such things are annoying for user and should be avoided.   
So it is a bit more work than just add bigger figures to options...

(slight remark - to improve readability, playing with color combinations may help.)

**Comment by Bono1969** [comment]
@hotNipi  I hope you did not understand my wish as a just do it is so simple.
You are the Designer and know exactly what is possible under which circumstances. Im only a User who is searching for a Solution which fits my needs. Off coarse you have to consider for all scenarios.
I hope you find a "dynamic" Solution for future Versions 👍

**Comment by hotNipi** [comment]
No problems :) And I did what was possible and reasonable.
With version 0.1.46 the radial layout gives more options for line thickness but only if the layout size is at least 4x4 units. No change for linear layout as there is no space for that.

**Comment by Bono1969** [comment]
@hotNipi 
Fantastic 👍👌👏 work fine.
Maybe you could think about the Linear Version, stretched to the hight of 2?

For the Moment thanks for the fantastic Support and the creating of the new Version 🎁

**Comment by hotNipi** [comment]
With version 0.1.47 (already published and will be available shortly) the linear layout has support for 2 units height and up to 25px line thickness. (slightly bigger texts and icon to preserve graphical balance)

![image](https://user-images.githubusercontent.com/35291460/88921870-eac5e380-d277-11ea-9a23-cb00a601825f.png)

**Comment by Bono1969** [comment]
@hotNipi 
you are suuuper 👌👍

**Comment by hotNipi** [comment]
Oh not that much, made mistake so 0.1.48 will be a bit better version (shortly available)
