### ISSUE TITLE
Safari hangs when going to the dashboard if 'Tickmarks' is checked - Chrome and FireFox work fine 

### ISSUE THREAD

**Issue by juggledad** [hotNipi/node-red-contrib-ui-artless-gauge#17]
macOS Mojave 10.14.6
Safari 14.0
12 Nov 04:58:23 - [info] Node-RED version: v1.1.3
12 Nov 04:58:23 - [info] Node.js  version: v12.13.0
Dashboard version 2.23.4
node-red-contrib-ui-artless-gauge v0.1.48

How to reproduce
1) add node-red-contrib-ui-artless-gauge to a new flow
2) set the 'Tab' ad 'Group' to the default
3) Deploy and go to dashboard - the node will show up
4) close the dashboard window
5) click the "Tickmarks' option
6) deploy and go to the dashboard

at this point (using Activity Monitor) Safari jumps to 100% cpu usage and after closing the dashboard window, the node-red editor window is blank and must be closed and opened to get back to the editor (which reloads).

**Comment by juggledad** [comment]
Oops, I thought it didn't post

**Comment by hotNipi** [comment]
Thanks for reporting. I don't have any mac to test so it may take some time to get fixed. But I'll check the possible faults in area anyway.
