### ISSUE TITLE
[FR] Bar with multiple sectors

### ISSUE THREAD

**Issue by IVI053** [hotNipi/node-red-contrib-ui-artless-gauge#2]
It would be great if there would be an option (checkbox) to enable bar with multiple sections in different colors.

Example:
Min: 0 green
Sec: 70 yellow
Sec: 80 red
Max: 100

With the option ticked it it would show a bar with it's first 70% percent green, than 10% yellow and 20% red when a value of 100 is received. At the moment the whole bar would be colored red.

**Comment by hotNipi** [comment]
This gauge will not get this option. Same request has many times rise for justgauge library and also not made. Two main reasons. It is quite complicated thing to do reliably with precision in mind. It will be reasonable for gauge with needle but for track only, the readability will not gain.

I can't invest my time into something with low value, but source is open and PR always welcome.

**Comment by IVI053** [comment]
That's sad. I did not want to improve readability but put more information into one bar. I have a battery with a dynamic low level and wanted to display the limited part of the SoC in one color and the usable in another.

I'm not into the whole JS/Nodered ecosystem so I'm not able provide any useful help on coding in it. :-(

**Comment by hotNipi** [comment]
Version 0.1.17 includes option to show small colored dots to indicate sector positions on the track. I know it is not the color-segmented line but better than nothing.
Closing issue with this.

**Comment by IVI053** [comment]
Thank you. This did help.
