### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by mediaessenz** [hotNipi/node-red-contrib-ui-artless-gauge#20]
I tried to install this node in my node red system running in a docker environment on a synology nas.

Unfortunately the installation fails with this error:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined (line:1185)

I already installed several other nodes without any problems, so it does not seams to be a general problem in my setup.

**Comment by hotNipi** [comment]
Hard to say anything. I have zero experiences on synolgy nas. And can't do any tests. 
The path is used in artless-gauge to load external library at front-end side, but it us used same way as all other nodes use it so can't really see it should be problematic. 

But seeing many posts about with problems of installation in terms of synology and docker so it may be tricky.  
Google search in therms mostly indicate nodejs version problems.

**Comment by mediaessenz** [comment]
I'm using the official docker image nodered/node-red:latest with the node red version 1.2.7. 
This image brings Node.js 10.23.1 within, which is definately not the hotest stuff, but quite close to the latest version of this branch (10.24.0).

The strange thing is, that I already using around 10 third party node-red packages (palette) without any issues.

Where exactly is this "path" command used, so may I can see any possible issues?

**Comment by mediaessenz** [comment]
Maybe it's this line: https://github.com/hotNipi/node-red-contrib-ui-artless-gauge/blob/00ea98f0e81d7acb1a81d8f33fe0d28a3b7d7ae1/ui-artless-gauge.js#L1178

```
if (RED.settings.ui) {
	uipath = RED.settings.ui.path;
}
```

Since the if condition only checks for the existing RED.settings.ui, there is no guarantee, that there is also a subproperty path.
If it doesn't exists (why ever), the value uipath will become "undefined" which is not a valid string and the following path command fails.

**Comment by mediaessenz** [comment]
Maybe I found the problem.

I added a middleware to the ui node inside my settings.js to get an own favicon:
```
ui: {
        middleware: function (req, res, next) {
            path = require('path')
            if (['/icon64x64.png', '/icon120x120.png', '/icon192x192.png'].includes(req.url)) {
                res.sendFile(path.resolve(path.join('/data/icons', req.url)))
            } else {
                next()
            }
        }
    }
  ```
  Could it be, that this kills the origin path sub property?

**Comment by mediaessenz** [comment]
Bingo: https://gist.github.com/mohnen/6923d5eb2e4547bb7e5bd90546d2ee80#gistcomment-3581744

**Comment by mediaessenz** [comment]
It's exaclty the problem. 

After changing the upper code to:
```
ui: {
        middleware: function (req, res, next) {
            path = require('path')
            if (['/icon64x64.png', '/icon120x120.png', '/icon192x192.png'].includes(req.url)) {
                res.sendFile(path.resolve(path.join('/data/icons', req.url)))
            } else {
                next()
            }
        },
        path: "ui"
    }
```
the installation of your package works without any issues.

Sorry for the false alarm.

**Comment by hotNipi** [comment]
Thanks to making things clear. 
And strange it didn't popped up for my search attempts. 
But all good 👍
