### ISSUE TITLE
Main value ist shifted when using the secondary input

### ISSUE THREAD

**Issue by sfh-soem** [hotNipi/node-red-contrib-ui-artless-gauge#21]
Hello, I've found the following small issue, if I use the secondary input: Is a unit defined for the main value, then everything looks fine (picture 1). If I don't define a unit, then the main value is shifted to left (picture 2). Probably there is a space on the right side (marked in picture 3).

![pic1](https://user-images.githubusercontent.com/64430377/111214641-735c7e80-85d2-11eb-98d1-d36b325130b8.png)
![pic2](https://user-images.githubusercontent.com/64430377/111214650-76576f00-85d2-11eb-9805-32b702a089b3.png)
![pic3](https://user-images.githubusercontent.com/64430377/111214656-79eaf600-85d2-11eb-9d94-e651afaa185e.png)

**Comment by hotNipi** [comment]
Fixed but with minor drawback - if unit  is configured to be empty, no way to show it with control message. So if needed to be dynamically changed, the initial configuration should contain something.
