### ISSUE TITLE
Configuring max color programmatically does not work on linear

### ISSUE THREAD

**Issue by jtheoret-hardt** [hotNipi/node-red-contrib-ui-artless-gauge#24]
I have created a linear widget and I am configuring it with the following code in a function node:

`const setpoint = global.get('temperature.setpoint');`
`const offset = 0.25;`
`let min = Math.round((setpoint - (setpoint * offset))/10) * 10;`
`let max = Math.round((setpoint + (setpoint * offset))/10) * 10;`
`var newSectors = [{t:"min",val:min,col:"#0000ff",dot:3},`
`                  {t:"sec",val:setpoint,col:"#00ff00",dot:3},`
`                  {t:"max",val:max,col:"#ff0000",dot:3}]`
`msg.control = {sectors:newSectors}`
`msg.setpoint = setpoint;`
`return msg;`

The max point shows green (#00FF00) instead of red (#FF0000)

**Comment by hotNipi** [comment]
It does work as expected. See, if you try to set color for max from the configuration, it does not allow to change it. It takes color of highest sector. But you still can achieve what you are trying by adding one extra sector before max. With just a little bit under the  max value.

```
const setpoint = global.get('temperature.setpoint');
const offset = 0.25;
let min = Math.round((setpoint - (setpoint * offset))/10) * 10;
let max = Math.round((setpoint + (setpoint * offset))/10) * 10;
let preMax = max - 0.0001 
var newSectors = [{t:"min",val:min,col:"#0000ff",dot:3},
{t:"sec",val:setpoint,col:"#00ff00",dot:3},
{t:"sec",val:preMax,col:"#ff0000",dot:0},
{t:"max",val:max,col:"#ff0000",dot:3}]
msg.control = {sectors:newSectors}
msg.setpoint = setpoint;
return msg;
```

**Comment by jtheoret-hardt** [comment]
Thank you very much, understood!
