### ISSUE TITLE
Hide value

### ISSUE THREAD

**Issue by ghost** [hotNipi/node-red-contrib-ui-artless-gauge#25]
Hi,
It's possible to hide the value?

![xxx](https://user-images.githubusercontent.com/81916825/150959117-16465c80-8396-41b7-9555-d8ae50780a7c.png)

**Comment by hotNipi** [comment]
There isn't any configuration option for that but you can use CSS to make it disappear.

![image](https://user-images.githubusercontent.com/35291460/151123292-cbb813b9-a3ff-406f-b5f6-cc0a13e7ff57.png)

**Comment by ghost** [comment]
Ok, thank you ....
