### ISSUE TITLE
No permanent display of the dynamic min max values

### ISSUE THREAD

**Issue by User1Peter** [hotNipi/node-red-contrib-ui-artless-gauge#26]
At runtime, the Min and Max values are passed to the artless-gauge-node.
After the deploy, these also appear in the template in the display.
The range is also displayed correctly with the new values.
After a page update, however
then the original values are displayed again.
The range min max remains unchanged. It only affects the display.

**Comment by hotNipi** [comment]
Front-end part of code has no options to store anything. Every time the widget is created from scratch (page reload, change tabs) it can use only default values from configuration. However, there is built-in replayMessage system at the server side. It remembers latest message and when dashboard connection is created - every widget gets that message. Now it really depends what was in that latest message. It can contain options for configuration override but it also can be simple message with the value only. 

This all means that if you use control messages to change default configuration at runtime, you also need to be sure that those changes will be sent to the widget in any case when widget is created (page reload, tab change)

To do so, you'll need to use the ui_control node as the trigger.
After that you'll need to determine all parameters you'll need to send to the widget. (only you know what is the current situation)
And then send the control message.

Example flow:
`[{"id":"2a8d6a1b1636e670","type":"ui_artlessgauge","z":"afcfe6f7a144f0b4","group":"d129285e4b08a665","order":0,"width":0,"height":0,"name":"","icon":"fa-fire","label":"Gauge","unit":"km","layout":"linear","decimals":0,"differential":false,"minmax":false,"colorTrack":"#555555","style":"","colorFromTheme":true,"property":"payload","secondary":"secondary","inline":false,"animate":true,"sectors":[{"val":0,"col":"#ff9900","t":"min","dot":0},{"val":10,"col":"#ff9900","t":"max","dot":0}],"lineWidth":3,"bgcolorFromTheme":true,"diffCenter":"","x":1040,"y":540,"wires":[]},{"id":"8a9931c63ddf715b","type":"inject","z":"afcfe6f7a144f0b4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"14","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":230,"y":500,"wires":[["468db23d521c4844"]]},{"id":"468db23d521c4844","type":"random","z":"afcfe6f7a144f0b4","name":"","low":1,"high":10,"inte":"true","property":"payload","x":620,"y":500,"wires":[["be7ee17a0a54012e"]]},{"id":"64980d0d6a15ad9c","type":"ui_ui_control","z":"afcfe6f7a144f0b4","name":"","events":"all","x":240,"y":560,"wires":[["a713220455dfd017"]]},{"id":"40c0712dbf60271f","type":"change","z":"afcfe6f7a144f0b4","name":"","rules":[{"t":"set","p":"control","pt":"msg","to":"{\"icon\":\"fa-thermometer\",\"unit\":\"°C\"}","tot":"json"},{"t":"set","p":"payload","pt":"msg","to":"lastKnownValue","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":780,"y":540,"wires":[["2a8d6a1b1636e670"]]},{"id":"be7ee17a0a54012e","type":"change","z":"afcfe6f7a144f0b4","name":"store last payload","rules":[{"t":"set","p":"lastKnownValue","pt":"flow","to":"payload","tot":"msg"}],"action":"","property":"","from":"","to":"","reg":false,"x":790,"y":500,"wires":[["2a8d6a1b1636e670"]]},{"id":"ef7b2c5d3177ccdb","type":"change","z":"afcfe6f7a144f0b4","name":"thermometer","rules":[{"t":"set","p":"gaugeShows","pt":"flow","to":"thermometer","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":410,"y":640,"wires":[["a713220455dfd017"]]},{"id":"fd114534461f2f75","type":"inject","z":"afcfe6f7a144f0b4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":240,"y":640,"wires":[["ef7b2c5d3177ccdb"]]},{"id":"a1fa8b79d9d6a429","type":"change","z":"afcfe6f7a144f0b4","name":"distance","rules":[{"t":"set","p":"gaugeShows","pt":"flow","to":"distance","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":420,"y":600,"wires":[["a713220455dfd017"]]},{"id":"ecf1f8a607ef59b7","type":"inject","z":"afcfe6f7a144f0b4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":240,"y":600,"wires":[["a1fa8b79d9d6a429"]]},{"id":"a713220455dfd017","type":"switch","z":"afcfe6f7a144f0b4","name":"","property":"gaugeShows","propertyType":"flow","rules":[{"t":"eq","v":"thermometer","vt":"str"},{"t":"else"}],"checkall":"true","repair":false,"outputs":2,"x":610,"y":560,"wires":[["40c0712dbf60271f"],["557e8938d4330729"]]},{"id":"557e8938d4330729","type":"change","z":"afcfe6f7a144f0b4","name":"","rules":[{"t":"set","p":"control","pt":"msg","to":"{\"icon\":\"fa-fire\",\"unit\":\"km\"}","tot":"json"},{"t":"set","p":"payload","pt":"msg","to":"lastKnownValue","tot":"flow"}],"action":"","property":"","from":"","to":"","reg":false,"x":780,"y":580,"wires":[["2a8d6a1b1636e670"]]},{"id":"d129285e4b08a665","type":"ui_group","name":"Select Station","tab":"85850867b381145e","order":1,"disp":true,"width":"6","collapse":false},{"id":"85850867b381145e","type":"ui_tab","name":"Trains","icon":"dashboard","disabled":false,"hidden":false}]`

**Comment by User1Peter** [comment]
Many thanks for the quick response.
did a little experimenting and one
Found the setting that works for my purposes
is working. I don't know why though! 

See flows.

[{"id":"1d99807e.aa8de","type":"ui_artlessgauge","z":"94891249.ca12e","group":"5c2ad9bc.fc0618","order":5,"width":3,"height":3,"name":"Day Value ","icon":"fa-fire","label":"Day","unit":"m³","layout":"radial","decimals":0,"differential":false,"minmax":true,"colorTrack":"#555555","style":"0,0, round","colorFromTheme":true,"property":"payload","secondary":"secondary","inline":true,"animate":true,"sectors":[{"val":0,"col":"#ff7f50","t":"min","dot":0},{"val":1,"col":"#ff7f50","t":"max","dot":0}],"lineWidth":"5","bgcolorFromTheme":true,"diffCenter":"","x":730,"y":80,"wires":[]},{"id":"ff3496f9.8b2558","type":"function","z":"94891249.ca12e","name":"","func":"var max = msg.payload;\nmax = max;\nmax = max.toFixed(0);\n\nvar newSectors =  [{t:\"min\",val: 0, col:\"rgb(255,127,80)\"},\n                   {t:\"max\",val:max}\n                  ]\n                    \nmsg.control =   {decimals:0, sectors:newSectors}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":520,"y":80,"wires":[["1d99807e.aa8de"]]},{"id":"79337137.c2fa4","type":"delay","z":"94891249.ca12e","name":"delay 2 sec","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":630,"y":160,"wires":[["8bb5441b.da0c48"]]},{"id":"8bb5441b.da0c48","type":"change","z":"94891249.ca12e","name":"","rules":[{"t":"set","p":"control","pt":"msg","to":"{\"icon\":\"fa-fire\",\"unit\":\"m³\"}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":870,"y":160,"wires":[["1d99807e.aa8de"]]},{"id":"2e8cc1b8.e68f1e","type":"inject","z":"94891249.ca12e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":150,"y":160,"wires":[["6c5cf6ff.d34638"]]},{"id":"3d4fef31.af201","type":"inject","z":"94891249.ca12e","name":"yesterday","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"86400","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"20","payloadType":"num","x":150,"y":80,"wires":[["ff3496f9.8b2558","6c5cf6ff.d34638"]]},{"id":"6c5cf6ff.d34638","type":"random","z":"94891249.ca12e","name":"current daily consumption value","low":1,"high":"19","inte":"true","property":"payload","x":390,"y":160,"wires":[["79337137.c2fa4"]]},{"id":"f0029e54.85ccd","type":"ui_artlessgauge","z":"94891249.ca12e","group":"5c2ad9bc.fc0618","order":5,"width":3,"height":3,"name":"Day Value ","icon":"fa-fire","label":"Day","unit":"m³","layout":"radial","decimals":0,"differential":false,"minmax":true,"colorTrack":"#555555","style":"0,0, round","colorFromTheme":true,"property":"payload","secondary":"secondary","inline":true,"animate":true,"sectors":[{"val":0,"col":"#ff7f50","t":"min","dot":0},{"val":1,"col":"#ff7f50","t":"max","dot":0}],"lineWidth":"5","bgcolorFromTheme":true,"diffCenter":"","x":730,"y":284,"wires":[]},{"id":"172611f6.c0f9fe","type":"function","z":"94891249.ca12e","name":"","func":"var max = msg.payload;\nmax = max;\nmax = max.toFixed(0);\n\nvar newSectors =  [{t:\"min\",val: 0, col:\"rgb(255,127,80)\"},\n                   {t:\"max\",val:max}\n                  ]\n                    \nmsg.control =   {decimals:0, sectors:newSectors}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":520,"y":284,"wires":[["f0029e54.85ccd"]]},{"id":"f97dc43c.b8f248","type":"delay","z":"94891249.ca12e","name":"delay 2 sec","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":690,"y":360,"wires":[["f0029e54.85ccd"]]},{"id":"821cb9c8.91f7b8","type":"inject","z":"94891249.ca12e","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":150,"y":360,"wires":[["209f5bb8.cb56d4"]]},{"id":"797664c8.89b88c","type":"inject","z":"94891249.ca12e","name":"yesterday","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"86400","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"20","payloadType":"num","x":150,"y":284,"wires":[["172611f6.c0f9fe","209f5bb8.cb56d4"]]},{"id":"209f5bb8.cb56d4","type":"random","z":"94891249.ca12e","name":"current daily consumption value","low":1,"high":"19","inte":"true","property":"payload","x":430,"y":360,"wires":[["f97dc43c.b8f248"]]},{"id":"b1ce9b5f.16da18","type":"comment","z":"94891249.ca12e","name":"Comment 1","info":"# This constellation works","x":130,"y":40,"wires":[]},{"id":"5524326f.00905c","type":"comment","z":"94891249.ca12e","name":"Comment 2","info":"# This constellation works  not","x":130,"y":240,"wires":[]},{"id":"5c2ad9bc.fc0618","type":"ui_group","name":"Erdgasverbrauch","tab":"b69e0370.e87b7","order":1,"disp":true,"width":"6","collapse":false,"className":""},{"id":"b69e0370.e87b7","type":"ui_tab","name":"Verbrauchsdaten","icon":"dashboard","order":4,"disabled":false,"hidden":false}]

**Comment by hotNipi** [comment]
Can't import your flow. 
Use this to share code. 
![image](https://user-images.githubusercontent.com/35291460/153358099-b439aa6d-514d-498f-b908-e9fe99d67412.png)

**Comment by User1Peter** [comment]
`[{"id":"1d99807e.aa8de","type":"ui_artlessgauge","z":"94891249.ca12e","d":true,"group":"5c2ad9bc.fc0618","order":5,"width":3,"height":3,"name":"Day Value ","icon":"fa-fire","label":"Day","unit":"m³","layout":"radial","decimals":0,"differential":false,"minmax":true,"colorTrack":"#555555","style":"0,0, round","colorFromTheme":true,"property":"payload","secondary":"secondary","inline":true,"animate":true,"sectors":[{"val":0,"col":"#ff7f50","t":"min","dot":0},{"val":1,"col":"#ff7f50","t":"max","dot":0}],"lineWidth":"5","bgcolorFromTheme":true,"diffCenter":"","x":730,"y":80,"wires":[]},{"id":"ff3496f9.8b2558","type":"function","z":"94891249.ca12e","name":"","func":"var max = msg.payload;\nmax = max;\nmax = max.toFixed(0);\n\nvar newSectors =  [{t:\"min\",val: 0, col:\"rgb(255,127,80)\"},\n                   {t:\"max\",val:max}\n                  ]\n                    \nmsg.control =   {decimals:0, sectors:newSectors}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":520,"y":80,"wires":[["1d99807e.aa8de"]]},{"id":"79337137.c2fa4","type":"delay","z":"94891249.ca12e","name":"delay 2 sec","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":630,"y":160,"wires":[["8bb5441b.da0c48"]]},{"id":"8bb5441b.da0c48","type":"change","z":"94891249.ca12e","name":"","rules":[{"t":"set","p":"control","pt":"msg","to":"{\"icon\":\"fa-fire\",\"unit\":\"m³\"}","tot":"json"}],"action":"","property":"","from":"","to":"","reg":false,"x":870,"y":160,"wires":[["1d99807e.aa8de"]]},{"id":"2e8cc1b8.e68f1e","type":"inject","z":"94891249.ca12e","d":true,"name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":150,"y":160,"wires":[["6c5cf6ff.d34638"]]},{"id":"3d4fef31.af201","type":"inject","z":"94891249.ca12e","d":true,"name":"yesterday","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"86400","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"20","payloadType":"num","x":150,"y":80,"wires":[["ff3496f9.8b2558","6c5cf6ff.d34638"]]},{"id":"6c5cf6ff.d34638","type":"random","z":"94891249.ca12e","name":"current daily consumption value","low":1,"high":"19","inte":"true","property":"payload","x":390,"y":160,"wires":[["79337137.c2fa4"]]},{"id":"f0029e54.85ccd","type":"ui_artlessgauge","z":"94891249.ca12e","d":true,"group":"5c2ad9bc.fc0618","order":5,"width":3,"height":3,"name":"Day Value ","icon":"fa-fire","label":"Day","unit":"m³","layout":"radial","decimals":0,"differential":false,"minmax":true,"colorTrack":"#555555","style":"0,0, round","colorFromTheme":true,"property":"payload","secondary":"secondary","inline":true,"animate":true,"sectors":[{"val":0,"col":"#ff7f50","t":"min","dot":0},{"val":1,"col":"#ff7f50","t":"max","dot":0}],"lineWidth":"5","bgcolorFromTheme":true,"diffCenter":"","x":730,"y":284,"wires":[]},{"id":"172611f6.c0f9fe","type":"function","z":"94891249.ca12e","name":"","func":"var max = msg.payload;\nmax = max;\nmax = max.toFixed(0);\n\nvar newSectors =  [{t:\"min\",val: 0, col:\"rgb(255,127,80)\"},\n                   {t:\"max\",val:max}\n                  ]\n                    \nmsg.control =   {decimals:0, sectors:newSectors}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":520,"y":284,"wires":[["f0029e54.85ccd"]]},{"id":"f97dc43c.b8f248","type":"delay","z":"94891249.ca12e","name":"delay 2 sec","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":690,"y":360,"wires":[["f0029e54.85ccd"]]},{"id":"821cb9c8.91f7b8","type":"inject","z":"94891249.ca12e","d":true,"name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"10","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":150,"y":360,"wires":[["209f5bb8.cb56d4"]]},{"id":"797664c8.89b88c","type":"inject","z":"94891249.ca12e","d":true,"name":"yesterday","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"86400","crontab":"","once":true,"onceDelay":0.1,"topic":"","payload":"20","payloadType":"num","x":150,"y":284,"wires":[["172611f6.c0f9fe","209f5bb8.cb56d4"]]},{"id":"209f5bb8.cb56d4","type":"random","z":"94891249.ca12e","name":"current daily consumption value","low":1,"high":"19","inte":"true","property":"payload","x":430,"y":360,"wires":[["f97dc43c.b8f248"]]},{"id":"b1ce9b5f.16da18","type":"comment","z":"94891249.ca12e","name":"Comment 1","info":"# This constellation works","x":130,"y":40,"wires":[]},{"id":"5524326f.00905c","type":"comment","z":"94891249.ca12e","name":"Comment 2","info":"# This constellation works  not","x":130,"y":240,"wires":[]},{"id":"5c2ad9bc.fc0618","type":"ui_group","name":"Erdgasverbrauch","tab":"b69e0370.e87b7","order":1,"disp":true,"width":"6","collapse":false,"className":""},{"id":"b69e0370.e87b7","type":"ui_tab","name":"Verbrauchsdaten","icon":"dashboard","order":4,"disabled":false,"hidden":false}]`

**Comment by hotNipi** [comment]
As I described previously - server side remembers last message and if it contains the control part, it will override configured defaults in case of page reload. 
First flow works, because of msg.control is sent with every payload. So `msg.control` is remembered and sent to the widget in case of reload. 
Second flow sends msg.control only when you do Deploy and the once a day. That means all other messages are contain only the value. There is no way for widget to remember the control part or figure it out somehow. 

Still, examine my example and read about the ui_control node. This is one and only proper way to guarantee updated state for dashboard widgets.

**Comment by User1Peter** [comment]
Thanks again for the examples and help. I'll deal with it in detail. I'm just at the beginning of my learning curve.
