### ISSUE TITLE
material icons not working

### ISSUE THREAD

**Issue by IVI053** [hotNipi/node-red-contrib-ui-artless-gauge#4]
When setting a material icon e.g. "dashboard" it ends up with the char "n" in the HTML source of the ui. It's always "n" in my tests and is never showing an icon. fa icons work fine.

**Comment by hotNipi** [comment]
May you try mi-dashboard

**Comment by IVI053** [comment]
What do you mean by "mi-dashboard"?

**Comment by hotNipi** [comment]
For material icons use prefix "mi-"
