### ISSUE TITLE
Value Color is invisible

### ISSUE THREAD

**Issue by chaos511** [hotNipi/node-red-contrib-ui-artless-gauge#5]
I am having the same issue as #1  
![Capture](https://user-images.githubusercontent.com/43281665/77837397-a17d5000-712e-11ea-8cd9-b79c1470ca1a.PNG)

Node-Red: v0.20.7
Dashboard: v2.15.4
artless-gauge: v0.1.16

**Comment by hotNipi** [comment]
Examine dashboard page with browser dev tools console to see if there is errors. I see the versions you are using are not latest. I can't immediately say if those versions are supported cos gauge is made with much later versions. But if there is errors, it may reveal at least some reasons.

**Comment by chaos511** [comment]
I don't know what fixed it but now it works, I installed it with the palette manager so rebooting is usually not required but some time after the install instal I restarted node-red so I don't know if that fixed it or if it was something else.

**Comment by hotNipi** [comment]
It may require reboot, sometimes. It really may depend your setup. Hard to tell. But if worked, everything is OK.
