### ISSUE TITLE
Some fa icons overlap bar

### ISSUE THREAD

**Issue by EvertDekker** [hotNipi/node-red-contrib-ui-artless-gauge#6]
Some font awesome icons overlap the bar, for example the[ fa-battery-half](https://fontawesome.com/v4.7.0/icon/battery-half) icon

![Capture](https://user-images.githubusercontent.com/5690965/78188030-d3185300-746f-11ea-91dc-3148bd9042ca.PNG)

**Comment by hotNipi** [comment]
Please add version of artless-gauge, you are using

**Comment by EvertDekker** [comment]
Sorry, complete forgot to mention.

node-red-contrib-ui-artless-gauge 0.1.17
Node-red 1.0.3
Dashboard 2.19.3

**Comment by hotNipi** [comment]
Will be fixed shortly.

**Comment by hotNipi** [comment]
Fixed in 0.1.19

**Comment by EvertDekker** [comment]
Looks great again.

![Capture](https://user-images.githubusercontent.com/5690965/78235362-d562c780-74d8-11ea-8b89-e469ed2e4046.PNG)

Thanks for the quick fix and thanks for this nice gauge.
