### ISSUE TITLE
Node config - Max Min range headings are hidden

### ISSUE THREAD

**Issue by borpin** [hotNipi/node-red-contrib-ui-artless-gauge#8]
The headings are hidden. I presume they should be Max and Min?

![image](https://user-images.githubusercontent.com/1322749/79681015-dd777280-820d-11ea-9f5d-5bd0a452122b.png)

**Comment by hotNipi** [comment]
This is issue with node-red core, known and will be fixed in next release I hope. https://discourse.nodered.org/t/node-red-1-0-5-released/24522

**Comment by borpin** [comment]
Ok great, thanks.
