### ISSUE TITLE
Show the sec values

### ISSUE THREAD

**Issue by calcioscacchi** [hotNipi/node-red-contrib-ui-artless-gauge#9]
Hi! I would like to see the values for the two secs that I've set, and not only for min and max values. Is it possible?

![image](https://user-images.githubusercontent.com/60674280/79810501-84295380-8373-11ea-8bf0-466858d33059.png)
![image](https://user-images.githubusercontent.com/60674280/79810528-8db2bb80-8373-11ea-91f0-6828a9df4607.png)

**Comment by hotNipi** [comment]
No and no plans to implement. It is way harder to do than it looks like.  With radial layout it has no free space so overlapping is unavoidable.
